### PR TITLE
Add language server

### PR DESCRIPTION
**Pull request by david072**
This adds a language server located in `server/`, and I moved the client / extension into `client/`. 
Language server features:

- Diagnostics: The language server checks the code and shows errors if something is wrong (Currently re-parses the whole file everytime something changes. The problem is that you can't just re-parse a single line since if you change the tick / tools this also needs to apply to lines that are further down. This also applies if you change the number of iterations of a repeat block. I will be opening an issue for that when this gets merged)
- Completion for the `start`, `repeat` and `end` statements and the tools, including their arguments (it also doesn't suggest argument that have already been given to the tool). It will also provide some information about the tool / argument you have currently selected.
- Access points for the tick of a line and the active tools of a line, which the client uses (=> the client code for that was removed)
- Information about the tool / argument you are hovering over (same information as completion gives you)

**Before starting the extension, run** `npm install` **and** `npm run compile` **in the root folder. That will install all of the necessary dependencies for the client and the server.**

### CODE REVIEW

**Comment by RainbowwPhoenixx** [comment]
Oh wow that is a lot! I'll be looking at this in detail over the next few days, looks clean

**Comment by RainbowwPhoenixx** [comment]
Here's a couple issues I found
- start:
    - start types save and map indicate the save/map name is ignored.
    - autocompletion still suggest start types after one is provided

- active tools display
    - only allow one tool of a type in active tools
    ```
    start now
    1>||||strafe vec
    2>||||strafe vec
    ```
    will show two strafe tools active
    - doesn't show on framebulks with less than three "|" ex:
    ```
    start now
    1>||||strafe vec
    2>
    ```
    clicking on the first bulk then on the last will make it so the active tools display stays stuck on the first bulk
- other
    - starting a multiline comment in the middle of a bulk will still show errors in the commented section
    ```
    start now
    1>||||strafe vec /*
    2>test */
    ```
    test will be underlined red
    - autocompletion will happen in comments in certain situations:
    `10>||||`
    typing "//" followed by a space at the end of the given line will give tool suggestion

**Comment by david072** [comment]
Oh shit these are some dumb issues. I'll look into them later

**Comment by david072** [comment]
Alright, should be all fixed :)

**Comment by RainbowwPhoenixx** [comment]
Found that one of the changes introduced a weird issue:
```
start now
0>
```
is just fine, but
```
start now

0>
```
Creates an error saying that it expected a tick greater than 0

**Comment by david072** [comment]
Ok, fixed that too

**Comment by RainbowwPhoenixx** [comment]
One more! I'm not sure whether I missed it before or if it was just introduced:
```
start now
0>||D1J1
```
an error is wrongly reported on the second "1"

**Pull request merged**
