### PR TITLE
Add a feature to see the active tools for a line

### PR DESCRIPTION
**Pull request by david072**
At the end of the line your cursor is in, you will now see a piece of non-editable piece of text that shows the active tools for that line and, if they take longer (e.g. lerped setang / autoaim), how many ticks are left. (#3)

I need to apologize for my inability to work with git again. I seem to have somehow duplicated the commits. Maybe you can still merge it since the diff shows the correct changes but if that doesn't work I honestly have no idea...

Commits that were added in the previous pull request:
- Add multiline comment highlighting (6f273f8)
- Add repeat support (18b66eb)
- Merge pull request #1 from david072/repeat-support (dd75eaa)
- Merge pull request #2 from david072/multiline-comments (31d546f)
- Optimise getTickForLine to look for previous absolute tick (151fbdc)
- Ignore multiline comments in getTickForLine() (d739d98)
- Add support for infinitely nested repeat blocks (aa09b5b)
- Move the code for ignoring multiline comments into a function (f5cc672)
- The contents of "Resolve merge conflicts" (7d4fbac)

### CODE REVIEW

**Comment by RainbowwPhoenixx** [comment]
Ok I was supposed to get a notification on my phone on PRs, but it doesn't appear to be working, so I'm once again sorry for the delay, feel free to ping/DM me on discord next time.
I'll look over this PR in the next few days

**Comment by mlugg** [comment]
Rainboww just gave me access to this repo for a but so I could deal with squashing this all into one commit - just waiting on him to test it now.
While rebasing, I figured out why your history is so weird (and how you had duplicate commits and stuff)! I can explain the technicalities to you on Discord if you'd like, but to fix it, you just need to reset your local `main` branch to the state of your remote one. To do that from the CLI, just run these commands:
```
git switch main
git fetch origin
git reset --hard origin/main
```
When you do PRs in future, if you can, you should make sure to do all your work on a separate branch (making sure it's based off of `main`) and PR that branch. This will help prevent issues like this in the future - feel free to drop me a message on the Discord if you need a hand at all :)

**Comment by david072** [comment]
Ok, thanks I'll do that. I actually had the changes in a separate branch, however I needed the changes from my main branch while the PR wasn't merged yet. I think the mistake might be that I merged the main branch into the branch with the changes and not the other way around.

**Comment by RainbowwPhoenixx** [comment]
Ok, I apologize for taking so long:
when placing the cursor on the 100> line in this script:
```
start now
0>||||setang 0 10
100>||||
```
the list says: `Active tools: setang`.
With this script:
```
start now
0>||||autoaim 4 5 6 10
100>||||
+5>||||autoaim off
```
on the line with 100>, it says `Active tools: autoaim (100 ticks left)`. A similar thing happens when giving a third argument to setang.

**Pull request merged**
